trigger:
  branches:
    include:
      - main  # Déclencher le pipeline automatiquement sur chaque push dans la branche "main".

pool:
  name: Default  # Remplacez par le nom de votre pool si vous utilisez un agent auto-hébergé.

steps:
# Étape 1 : Récupérer le code source
- checkout: self
  fetchDepth: 1

# Étape 2 : Construire et pousser l'image Docker vers Docker Hub
- task: Docker@2
  inputs:
    containerRegistry: 'az-dockerhub-connection'  # Connexion Docker Hub configurée dans Azure DevOps.
    repository: 'mounaoulbacha228/docker-image'      # Répertoire de l'image Docker (<utilisateur>/<nom-repo>).
    command: 'buildAndPush'                       # Construire et pousser l'image Docker.
    Dockerfile: 'Dockerfile'                      # Chemin relatif vers le Dockerfile.
    tags: 'latest'                                # Utiliser le tag "latest" pour l'image.

# Étape 3 : Déclencher le déploiement Render via un Deploy Hook
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Appeler l'URL du Deploy Hook pour déclencher le déploiement Render
      $url = "https://api.render.com/deploy/srv-ctb32md2ng1s73dpi7o0?key=f8x6Htnw6Qk"
      Invoke-RestMethod -Uri $url -Method Post
  displayName: 'Trigger Deploy via Render Hook'